### ISSUE TITLE
"delay=None" halts code execution 

### ISSUE THREAD

**Issue by ghost** [MaliciousFiles/WinToaster#1]
When setting ```delay=None``` the destroy functions are never called and thus it seems the program halts until the Toast is somehow destroyed.

Here is a snippet of my code:

```python
import win_toaster
import time

mytoast = win_toaster.create_toast(
    title="I am a Toast!",
    msg="Wow",
    icon_path="fish.ico",
    delay=None,
    sound_path="bazinga.wav",
    tooltip="Tooltip",
    threaded=False,
    duration=5,
    callback_on_click=open_url,
    kill_without_click=True,
)

while True:
    try:
        mytoast.display()
        print("Toast deployed, next one coming in 15 secs")
        time.sleep(15)
        continue   
    except Exception as e:
        print (e)
        print("No more toast?")

```     

I have thought about implementing a destroy function that would go something like this:

```python
mytoast.destroy_window = True
mytoast.toast_data["delay"] = 1
```

But it doesn't seem pretty.

Note: The program keeps running if ```threaded = True```, but wouldn't that solution leave opened threads indefinitely ?

**Comment by MaliciousFiles** [comment]
@ZedFuzz 

Hi! Thanks for making an issue, and I think the problem is that I forgot to finish the documentation. -_- I am curious, how did you figure out what all the arguments do? Looking at the source code?

Regardless, the issue is that if you want no delay after the toast (essentially a sleep function) you would do `0` not `None`. That being said, instead of doing `time.sleep(15)` afterwards you could just set the `delay` to `15`. Another thing to point out is that you're just setting `threaded`, `duration`, and `kill_without_click` to their default values so you don't really need to put those if you don't want to.

I will push an update so that if you do `None` it'll default to `0`, and also I found a bug where if you click the Toast it won't run the delay code, but I hope this fixes your issue!

EDIT: In answer to your questions about the thread, yes. Since it runs the code indefinitely, threading it will just make a thread stay forever.

EDIT 2: One thing to know about `delay`, I don't know if you care about this, is that it will leave the icon in the System Tray while it is waiting, though I am planning on changing that in my next push in a little bit.

**Comment by MaliciousFiles** [comment]
Ok I've done a bit of tinkering and my final verdict is that setting `delay` to `None` will keep the Tray Icon alive after the toast is gone, either good through the toast being clicked or the Icon being clicked. I'm going to change it to add a new parameter, `keep_alive` which will do that same thing, and make it so `delay` being `None` is the same as `delay` being `0`. While `keep_alive` is true, the way you destroy the toast is by calling `Toast#destroy`

**Comment by ghost** [comment]
@MaliciousFiles 

Hi, thanks for the quick reply. I did in fact read through your source code to find out how to use it. I like it much more than the original implementation of WinToast as it is fairly easy to read and follow along 👏

I also failed to express my objetive with this code snippet, allow me to reformulate. 
```python

mytoast = win_toaster.create_toast(
    title="I am a Toast!",
    msg="Wow",
    icon_path="fish.ico",
    delay=None,
    sound_path="bazinga.wav",
    tooltip="Tooltip",
    threaded=False,
    duration=5,
    callback_on_click=open_url,
    kill_without_click=True,
)

while True:
    try:
        mytoast.display()
        print("Toast deployed, next one coming in 15 secs")
        time.sleep(15)
        #My issue
        print ("This code never executes")
        continue   
    except Exception as e:
        print (e)
        print("No more toast?")
```

I did not mean to make a 0 delay Toast. My objective was to create a persistent Toast, one that would stick to the Tray area or Notification Center until dismissed/clicked while allowing for more Toast to be deployed.

Your ```keep_alive``` solution seems to solve this issue. I am curious, how will ```Toast#destroy``` work?

**Comment by MaliciousFiles** [comment]
@ZedFuzz

No problem, and thanks for the compliment and good job on reading the source code! `Toast#destroy` will just consolidate what already happens.

Previously, at the end of `Toast#display`, it did this:
```Python
if self.toast_data["delay"] is not None and self.destroy_window:
            while self.toast_data["delay"] > 0:
                sleep(0.1)
                self.toast_data["delay"] -= 0.1

            DestroyWindow(self.toast_data["hwnd"])
            UnregisterClass(
                self.toast_data["wnd_class"].lpszClassName, self.toast_data["hinst"]
            )
            try:  # Sometimes the try icon sticks around until you click it - this should stop that
                Shell_NotifyIcon(NIM_DELETE, (self.toast_data["hwnd"], 0))
            except WinTypesException:
                pass
```

And at the end of `Toast#wnd_proc` (which is the function that does the callback) it does:
```python
if self.toast_data["delay"] is not None and self.destroy_window:
    try:
        Shell_NotifyIcon(NIM_DELETE, (hwnd, 0))
    except WinTypesException:
        pass
    PostQuitMessage()
```

`Toast#destroy` will simply replace both of those and do:
```python
if not self.toast_data["keep_alive"] and self.destroy_window:
            delay = self.toast_data["delay"]
            while delay != None and delay > 0:
                sleep(0.1)
                delay -= 0.1

            try:
                DestroyWindow(self.toast_data["hwnd"])
            except WinTypesException:
                pass

            UnregisterClass(
                self.toast_data["wnd_class"].lpszClassName, self.toast_data["hinst"]
            )
            try:  # Sometimes the try icon sticks around until you click it - this should stop that
                Shell_NotifyIcon(NIM_DELETE, (self.toast_data["hwnd"], 0))
            except WinTypesException:
                pass

            PostQuitMessage()

            self.active = False
```

Sorry for the bad indentation :/

EDIT: when `keep_alive` is True, it will not hold up the rest of the program by the way

**Comment by MaliciousFiles** [comment]
Ok it's pushed, go ahead and download it then tell me if it works for you!

PS: I'm curious, what are you making?

**Comment by ghost** [comment]
> EDIT: when `keep_alive` is True, it will not hold up the rest of the program by the way
@MaliciousFiles 

It seems it ```keep_alive = True``` **does hold up** the rest of program, could you try the following code and verify ? Please disregard the icon and sound variables.

```python
mytoast = win_toaster.create_toast(
    title="I am a Toast!",
    msg="Wow",
    icon_path="fish.ico",
    delay=0,
    sound_path="bazinga.wav",
    tooltip="Tooltip",
    threaded=False,
    duration=5,
    keep_alive = True,
    callback_on_click=None,
    kill_without_click=True,
)

while True:
    try:
        mytoast.display()
        print("Toast deployed, next one coming in 15 secs")
        time.sleep(15)
        #My issue
        print ("This code never executes")
        continue   
    except Exception as e:
        print (e)
        print("No more toast?")

```
 The message ```This code never executes``` is never printed out. I am incorrectly implementing / instancing the class?

My take:
The Toast is created and awaits some sort of next execution (the flags ```keep_alive = True``` and ```kill_without_click = True``` do not currently trigger the destroy event). 

This seems fine, I assume the ```threaded``` option was created for situations like these where the code execution of the main method must go on despite the Toast waiting on an action.

What I attemped to do next was to create a ```callback_on_click``` to destroy the instanced Toast, but it did not work.

So, using this configuration and switching ```threaded``` to ```True``` (in order to not hold the program) will result in multiple indestroyable tray icons.
<img width="179" alt="icons" src="https://user-images.githubusercontent.com/18250527/128396524-28707ac6-1bcf-4ecd-9fa0-6533c70889a0.png">

**Comment by ghost** [comment]
> Ok it's pushed, go ahead and download it then tell me if it works for you!
> 
> PS: I'm curious, what are you making?

I was building a python monitor script for changes on a website when it occurred to me it would be handy to have a Toast notification coupled with Sheldon's bazinga.wav at maximum volume. Just doing it for the lulz

**Comment by MaliciousFiles** [comment]
Sorry, it was my mistake saying that `keep_alive` wouldn't hold up the program, it does. You are correct in using `threaded` in order to continue on the main thread. The indestructable icons will be removed when you close the program. The issue is on my end, I need to make a slight modification to `Toast#destroy`

EDIT: It is now pushed

**Comment by ghost** [comment]
Ah! How satisfying it feels to click the tray icons and watch them go away 😇

Thank you!
