### ISSUE TITLE
[FEATURE] Please ACTUALLY put documentation in your website.

### ISSUE THREAD

**Issue by FlookyBS** [MaliciousFiles/WinToaster#3]
**Is your feature request related to a problem? Please describe.**
Yes. There is 0 documentation on your website.

**Describe the solution you'd like**
Make clear and concise documentation on how to implement our library, with examples, and etc.

**Describe alternatives you've considered**
Documentation.

**Additional context**
wintoaster.readthedocs.io
![Captura de pantalla_2024-04-04_21-02-41](https://github.com/MaliciousFiles/WinToaster/assets/69437909/38e5de53-95f0-4a31-a21f-996cf7d7042f)

**Comment by MaliciousFiles** [comment]
Unfortunately I likely won't have time to get around to this for a while. However, there is documentation in the code itself. If your IDE doesn't allow you to see it already (most modern IDEs should), you can look at the source code. Here are a couple of screenshots:

![Screenshot 2024-04-04 at 7 11 48 PM](https://github.com/MaliciousFiles/WinToaster/assets/57738870/a229f2cd-7966-47a7-b5c1-03d916b62b39)
![Screenshot 2024-04-04 at 7 11 41 PM](https://github.com/MaliciousFiles/WinToaster/assets/57738870/ad95d8fd-eaf3-42cf-b60e-24a58d2ac0f3)

If that isn't sufficient, you are still confused, or something weird is happening, feel free to ask me directly or open another issue. Thank you!

EDIT: I just checked, and I even commented my code into general sections when I wrote it. Shouldn't be too difficult to answer any surface-level questions about what's going on. I will add a simple piece of code to the GitHub readme to show using the basic function.
